### ISSUE TITLE
Login authentication failed

### ISSUE THREAD

**Issue by JuniorGamingTime** [emiliobool/node-red-contrib-twitch-chat#1]
Trying to login to my twitch bot account and cant login. 
i disabled 2 step verification as well and still cant log in, is there something im missing?
Using Node-red version 0.20.7

**Comment by emiliobool** [comment]
Hi, are you using your regular password or are you using your oauth token? using your regular password is not allowed on the twitch api even if they call it "password", so you need to get an oauth token, you can easily get one from here: https://twitchapps.com/tmi/

make sure to prepend oauth: to the begining so it reads "oauth:xkldsajsdfkl"

**Comment by JuniorGamingTime** [comment]
Ohh I was not aware of that might wanna add it to the read me.
Is this something you're still developing or?

**Comment by emiliobool** [comment]
I personally still use it, I do have a list of improvements but nothing compelling enough for me to prioritize over other things so I haven't updated it recently. If you find any bugs or anything just let me know.

**Comment by JuniorGamingTime** [comment]
yeah no problem

**Comment by JuniorGamingTime** [comment]
Is there a way to test say the Follower and sub notifications coming in?

**Comment by emiliobool** [comment]
not really, everything is based off tmi.js but even on the site's dev docs you can't really see the data structure. In order to be able to see the structure and to test your flows, what I do is record everything, all events, you can then replay them from there. I mean you would need to setup something yourself but no that hard, then you can simply simulate the output and inject it into your flow. 

I think I was using mongodb before but I switched to rethinkdb to store all events, but you can basically use anything you want, mongodb would be faster, and depending on your specs an in memory key pair store (like redis) would be even faster.

Also a faster easier way that I was doing before is simply send the output to a debug node, and as long as you have node-red open you should be able to go back and copy paste the payload into an inject node.

**Comment by JuniorGamingTime** [comment]
Ok cool I already have a Streamlabs thing working with lights but I just wanted more control.
I'm still really new to nodered but I'll look into the ones you suggested.
Thanks alot

**Comment by emiliobool** [comment]
no problem.

**Comment by JuniorGamingTime** [comment]
Also by any chance do you have like a list that has a bit more info of what each node its capable off?

**Comment by emiliobool** [comment]
All nodes correspond to tmi.js functions, so you can use their docs. There are links pointing to the corresponding tmi.js docs link, so you can easily click on the node and you should see a link on the sidebar "[ tmi.js doc entry ]", just click it and it will take you to the docs page with a more detailed description on what you can do with it.

**Comment by emiliobool** [comment]
is the tmijs.org site down for you too? If it is you will need too check their docs on GitHub

**Comment by JuniorGamingTime** [comment]
Yeah I  checked last night and it was I can check later when I get home
