### ISSUE TITLE
Use this with reverse proxy?

### ISSUE THREAD

**Issue by hikuikuma** [emiliobool/node-red-contrib-twitch-chat#21]
Hello,
I've been using these nodes for a while and by the way thank you! But recently I switched to a Node-Red instance in http behind a reverse proxy which forces https. Except with this configuration, the config does not allow me to connect and I do not understand why. Should I allow a particular path to my instance through my reverse proxy?

A node tmi-config return this in debug
`"Login authentication failed"`

Thank you so much

**Comment by emiliobool** [comment]
Hi hikuikuma, it's been a while since I used/updated this plugin, I'll check if there is an easy fix but I don't think the problem is related to the proxy. Maybe a firewall could affect but I'm more inclined to think it is due to a more recent version of node-red, if I have to guess, when you switched to this new instance it was newer and probably incompatible, could you share what node-red version you are using now?

**Comment by emiliobool** [comment]
I just tested it with the latest version (I think), and one thing I got wrong the first time was that the password field it is meant to use your oauth token but it needs to start with "oauth:" so instead of just "ksadjfhsdg..." you need to add "oauth:ksadjfhsdg..." as password. Also regular passwords don't work (twitch deprecated them a long time ago). 

Hopefully that was your issue too.

**Comment by hikuikuma** [comment]
> could you share what node-red version you are using now?

It's Node-Red 3.0.2

> Hopefully that was your issue too.

Effectively using oauth:<access_token> and it works!
Thank you!

Are you going to make an update to include the connection via oauth directly in tmi-config?

Have nice day!
